name: build
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        agda-ref: ["v2.6.2"]
        agda-stdlib-ref: ["v1.7.1"]
        ghc-ver: ["9.0.1"]
        cabal-ver: ["3.4.0.0"]
        fira-code-ver: ["6.2.0"]

    steps:
    - name: cache cabal packages
      uses: actions/cache@v3
      id: cache-cabal
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          ~/.cabal/bin
          dist-newstyle
        key: ${{ runner.os }}-${{ matrix.ghc-ver }}-${{ matrix.cabal-ver }}-${{ matrix.agda-ref }}

    - name: install ghc and cabal
      if: steps.cache-cabal.outputs.cache-hit != 'true'
      uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc-ver }}
        cabal-version: ${{ matrix.cabal-ver }}

    - name: put cabal programs in PATH
      run: echo "~/.cabal/bin" >> $GITHUB_PATH

    - name: checkout agda
      if: steps.cache-cabal.outputs.cache-hit != 'true'
      uses: actions/checkout@v4
      with:
        repository: agda/agda
        path: agda
        ref: ${{ matrix.agda-ref }}

    - name: install agda
      if: steps.cache-cabal.outputs.cache-hit != 'true'
      run: |
        cabal update
        cd agda
        mkdir -p doc
        touch doc/user-manual.pdf
        cabal install --overwrite-policy=always --ghc-options='-O1 +RTS -M6G -RTS'

    - name: checkout agda-stdlib
      uses: actions/checkout@v4
      with:
        repository: agda/agda-stdlib
        path: agda-stdlib
        ref: ${{ matrix.agda-stdlib-ref }}

    - name: register agda-stdlib in library list
      run: |
        mkdir -p ~/.agda/
        touch ~/.agda/libraries
        echo "$GITHUB_WORKSPACE/agda-stdlib/standard-library.agda-lib" > ~/.agda/libraries

    - name: checkout this library
      uses: actions/checkout@v4
      with:
        path: main

    - name: cache this library
      uses: actions/cache@v3
      id: cache-main
      with:
        path: ~/main-build
        key: html-and-tex-${{ runner.os }}-${{ matrix.agda-ver }}-${{ matrix.agda-stdlib-ref }}-${{ hashFiles('main/**') }}
        restore-keys: |
          html-and-tex-${{ runner.os }}-${{ matrix.agda-ver }}-${{ matrix.agda-stdlib-ref }}-
          html-and-tex-${{ runner.os }}-${{ matrix.agda-ver }}-

    - name: retrieve cached library
      if: steps.cache-main.outputs.cache-hit == 'true'
      run: cp -f -R ~/main-build/* $GITHUB_WORKSPACE/main

    - name: compile library
      if: steps.cache-main.outputs.cache-hit != 'true'
      run: |
        mkdir -p ~/main-build/_build
        cp -f -R ~/main-build/_build $GITHUB_WORKSPACE/main/_build
        rm -r ~/main-build
        cd main
        source scripts/everything.sh index
        agda --html --highlight-occurrences --html-dir=docs src/index.agda
        rm src/index.agda
        cd ..
        cp -f -R main/ ~/main-build/

    - name: deploy html to github pages
      if: ${{ github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: main/docs
